import { RoomInfo } from "./types";

export const mockRoomInfo: RoomInfo = {
  id: "6201",
  lectures: [
    {
      id: "1",
      name: "소프트웨어공학",
      professor: "김철수",
      startTime: "09:00",
      endTime: "10:50",
      day: 0,
    },
    {
      id: "2",
      name: "데이터베이스",
      professor: "이영희",
      startTime: "11:00",
      endTime: "12:50",
      day: 0,
    },
    {
      id: "3",
      name: "알고리즘",
      professor: "박지훈",
      startTime: "14:00",
      endTime: "15:50",
      day: 0,
    },
    {
      id: "4",
      name: "운영체제",
      professor: "최민준",
      startTime: "09:00",
      endTime: "10:50",
      day: 1,
    },
    {
      id: "5",
      name: "컴퓨터네트워크",
      professor: "정수현",
      startTime: "13:00",
      endTime: "14:50",
      day: 1,
    },
    {
      id: "6",
      name: "인공지능",
      professor: "한도윤",
      startTime: "09:00",
      endTime: "11:50",
      day: 2,
      isGraduate: true,
    },
    {
      id: "7",
      name: "웹프로그래밍",
      professor: "임서연",
      startTime: "15:00",
      endTime: "16:50",
      day: 2,
    },
    {
      id: "8",
      name: "자료구조",
      professor: "오민재",
      startTime: "10:00",
      endTime: "11:50",
      day: 3,
    },
    {
      id: "9",
      name: "프로그래밍언어론",
      professor: "강태양",
      startTime: "13:00",
      endTime: "14:50",
      day: 3,
    },
    {
      id: "10",
      name: "소프트웨어공학",
      professor: "김철수",
      startTime: "09:00",
      endTime: "10:50",
      day: 4,
    },
    {
      id: "11",
      name: "캡스톤디자인",
      professor: "윤하늘",
      startTime: "14:00",
      endTime: "17:50",
      day: 4,
    },
  ],
  equipment: {
    seats: 31,
    seatNote: "강사 좌석 포함",
    outlets: 15,
    outletNote: "책상마다 3구 멀티탭",
  },
};
